#!/bin/bash

SESSION=env

if $1 && $(tmux has-session -t $SESSION 2> /dev/null); then
    echo 'Service already running' >&2
    return 1
fi
if $1; then
    tmux new-session -d -s $SESSION
    tmux send-keys -t $SESSION ./start_python C-m
fi
tmux attach-session -t $SESSION
